import Head from "next/head";
import { SpeechToTextForm } from "../src/components/speech-to-text-form";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Transcribe It!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Transcribe it!</h1>
        <SpeechToTextForm />
      </main>

      <footer className={styles.footer}>Powered by ZUMA</footer>
    </div>
  );
}
